version: '2.2'

volumes:
  # cache
  nix_store:

services:
  runner:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - WORKDIR=/app
    env_file:
      - ./aws.env
    environment:
      NIXOPS_DEPLOYMENT: foo
      NIXOPS_STATE: /app/state.nixops
    volumes:
      - nix_store:/nix/store

      - ./ssh_config:/etc/ssh/ssh_config
      - ./id_rsa:/ssh/id_rsa

      - ..:/app
      - ../../vd-rails:/backend
